# Generated by Django 4.2.16 on 2024-10-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_password'),
        ('favorites', '0002_remove_favorites_user_favorites_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='dish',
        ),
        migrations.AddField(
            model_name='favorites',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
