# Generated by Django 4.2.16 on 2024-10-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pick',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Preparing', 'Preparing'), ('Ready to pick', 'Ready to pick'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
    ]
