# Generated by Django 4.2.16 on 2024-10-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_pick_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_pick',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
